name: CI
on:
  push:
    branches:
      - dev
      - feature
  workflow_dispatch:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: "brands description topics"
  testing:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repo from github
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.13.2"

      - name: pip
        run: |
          pip install -r requirements.test.txt

      - name: pytest
        run: |
          # pytest --cov

  analyze:
    name: Analyze Python
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: github/codeql-action/init@v3
        with:
          languages: python

      - uses: github/codeql-action/autobuild@v3

      - uses: github/codeql-action/analyze@v3

  ci_complete:
    name: ci_complete
    runs-on: ubuntu-latest
    needs:
      - validate
      - analyze
      - testing
    timeout-minutes: 1
    steps:
      - run: echo 'finish job'
